version: '2'
services:
    cmasbids-app:
        image: cmasbids
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cmasbidsdb.c2cd28vpzu9q.us-west-1.rds.amazonaws.com:3306/cmasBids?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cmasbids-elasticsearch:9300
        ports:
            - 8080:8080
    cmasbids-mysql:
        extends:
            file: mysql.yml
            service: cmasbids-mysql
    cmasbids-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cmasbids-elasticsearch
